[colors.primary]
background = "#0c0e13"
foreground = "#e2e2e9"
dim_foreground = "#c5c6d0"
bright_foreground = "#e2e2e9"

[colors.cursor]
text = "#0c0e13"
cursor = "#aec6ff"

[colors.selection]
text = "#d8e2ff"
background = "#2c4678"

[colors.normal]
black = "#0c0e13"
red = "#ffb4ab"
green = "#dfbcdf"
yellow = "#bfc6dc"
blue = "#aec6ff"
magenta = "#d8e2ff"
cyan = "#fcd7fb"
white = "#e2e2e9"

[colors.bright]
black = "#1e1f25"
red = "#ffb4ab"
green = "#583e5a"
yellow = "#3f4759"
blue = "#2c4678"
magenta = "#aec6ff"
cyan = "#fcd7fb"
white = "#c5c6d0"
