
# Generated by matugen. DO NOT EDIT.

export COLOR_BACK='{{ colors.background.default.hex }}'
export COLOR_FORE='{{ colors.on_background.default.hex }}'

export COLOR01='{{ colors.surface_container_highest.default.hex }}'
export COLOR02='{{ colors.error.default.hex }}'
export COLOR03='{{ colors.tertiary.default.hex }}'
export COLOR04='{{ colors.secondary.default.hex }}'
export COLOR05='{{ colors.primary.default.hex }}'
export COLOR06='{{ colors.secondary.default.hex }}'
export COLOR07='{{ colors.tertiary.default.hex }}'
export COLOR08='{{ colors.surface_container_high.default.hex }}'

export COLOR09='{{ colors.outline.default.hex }}'
export COLOR10='{{ colors.error.default.hex }}'
export COLOR11='{{ colors.tertiary.default.hex }}'
export COLOR12='{{ colors.secondary.default.hex }}'
export COLOR13='{{ colors.primary.default.hex }}'
export COLOR14='{{ colors.secondary.default.hex }}'
export COLOR15='{{ colors.tertiary.default.hex }}'
export COLOR16='{{ colors.on_background.default.hex }}'
